apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    run: ${app.label}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ${app.label}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ${app.label}
    spec:
      containers:
      - ports:
        - containerPort: 8080