apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    expose: "true"
spec:
  selector:
    run: ${app.label}
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer